export default Object.freeze(
	[
		{
			id: "nextjs",
			name: "Next.js",
			documentationURL: "https://nextjs.org/docs",
			includePaths: [
				"next.config.js",
				'package.json:"next"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["reactjs"],
			weight: 4,
		},
		{
			id: "reactjs",
			name: "React",
			documentationURL: "https://reactjs.org/docs/getting-started.html",
			includePaths: [
				'package.json:"react"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
				"*.jsx",
				"*.tsx",
			],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 3,
		},
		{
			id: "javascript",
			name: "JavaScript",
			documentationURL:
				"https://developer.mozilla.org/en-US/docs/Web/JavaScript",
			includePaths: ["*.js", "*.jsx"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 0,
		},
		{
			id: "nodejs",
			name: "Node.js",
			documentationURL: "https://nodejs.org/api/all.html",
			includePaths: ["node_modules", "package.json", "package-lock.json"],
			blacklistedFilenames: ["node_modules"],
			ignoreTechs: ["javascript"],
			weight: 1,
		},
		{
			id: "typescript",
			name: "TypeScript",
			documentationURL: "https://www.typescriptlang.org/docs/",
			includePaths: ["*.ts", "*.tsx", "tsconfig.json"],
			blacklistedFilenames: ["node_modules", "tsconfig.json"],
			ignoreTechs: ["javascript"],
			weight: 1,
		},
		{
			id: "vite",
			name: "Vite",
			documentationURL: "https://vite.dev/guide/",
			includePaths: [
				"vite.*config.ts",
				"vite.*config.js",
				".vite",
				'package.json:"vite"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [".vite"],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "reactnative",
			name: "React Native",
			documentationURL: "https://reactnative.dev/docs/getting-started",
			includePaths: ['package.json:"react-native"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: ["reactjs"],
			weight: 4,
		},
		{
			id: "expo",
			name: "Expo",
			documentationURL: "https://docs.expo.dev/",
			includePaths: [
				'package.json:"expo"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
				".expo",
			],
			blacklistedFilenames: [],
			ignoreTechs: ["reactnative"],
			weight: 5,
		},
		{
			id: "python",
			name: "Python",
			documentationURL: "https://docs.python.org/",
			includePaths: ["*.py"],
			blacklistedFilenames: [".venv"],
			icnoreTechs: [],
			weight: 1,
		},
		{
			id: "bun",
			name: "Bun",
			documentationURL: "https://bun.com/docs/",
			includePaths: [
				'package.json:"bun"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
				"bun.lock",
				"bun.lockb",
			],
			blacklistedFilenames: ["bun.lock", "bun.lockb"],
			ignoreTechs: ["javascript", "nodejs"],
			weight: 1,
		},
		{
			id: "expressjs",
			name: "Express.js",
			documentationURL: "https://expressjs.com/",
			includePaths: ['package.json:"express"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 2,
		},
		{
			id: "java",
			name: "Java",
			documentationURL: "https://docs.oracle.com/",
			includePaths: ["*.java"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
	].toSorted((a, b) => a.weight - b.weight),
) as readonly Technology[];
