export default Object.freeze(
	[
		{
			id: "nextjs",
			name: "Next.js",
			documentationURL: "https://nextjs.org/docs",
			includePaths: [
				"next.config.js",
				'package.json:"next"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["reactjs"],
			weight: 4,
		},
		{
			id: "reactjs",
			name: "React",
			documentationURL: "https://reactjs.org/docs/getting-started.html",
			includePaths: [
				"*.jsx",
				"*.tsx",
				'package.json:"react"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["html"],
			weight: 3,
		},
		{
			id: "threejs",
			name: "Three.js",
			documentationURL: "https://threejs.org/docs/",
			includePaths: ['package.json:"three"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "javascript",
			name: "JavaScript",
			documentationURL:
				"https://developer.mozilla.org/en-US/docs/Web/JavaScript",
			includePaths: ["*.js", "*.jsx"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 0,
		},
		{
			id: "nodejs",
			name: "Node.js",
			documentationURL: "https://nodejs.org/api/all.html",
			includePaths: ["node_modules", "package.json", "package-lock.json"],
			blacklistedFilenames: ["node_modules"],
			ignoreTechs: ["javascript"],
			weight: 1,
		},
		{
			id: "typescript",
			name: "TypeScript",
			documentationURL: "https://www.typescriptlang.org/docs/",
			includePaths: ["*.ts", "*.tsx", "tsconfig.json"],
			blacklistedFilenames: ["node_modules", "tsconfig.json"],
			ignoreTechs: ["javascript"],
			weight: 1,
		},
		{
			id: "socketio",
			name: "Socket.OI",
			documentationURL: "https://socket.io/docs/",
			includePaths: ['package.json:"socket.io"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: ["javascript"],
			weight: 1,
		},
		{
			id: "reactnative",
			name: "React Native",
			documentationURL: "https://reactnative.dev/docs/getting-started",
			includePaths: ['package.json:"react-native"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: ["reactjs"],
			weight: 4,
		},
		{
			id: "expo",
			name: "Expo",
			documentationURL: "https://docs.expo.dev/",
			includePaths: [
				".expo",
				'package.json:"expo"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["reactnative"],
			weight: 5,
		},
		{
			id: "python",
			name: "Python",
			documentationURL: "https://docs.python.org/",
			includePaths: ["*.py"],
			blacklistedFilenames: [".venv"],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "expressjs",
			name: "Express.js",
			documentationURL: "https://expressjs.com/",
			includePaths: ['package.json:"express"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 2,
		},
		{
			id: "java",
			name: "Java",
			documentationURL: "https://docs.oracle.com/",
			includePaths: ["*.java"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "css",
			name: "CSS",
			documentationURL: "https://developer.mozilla.org/fr/docs/Web/CSS",
			includePaths: ["*.css"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "html",
			name: "HTML",
			documentationURL: "https://developer.mozilla.org/fr/docs/Web/HTML",
			includePaths: ["*.html", "*.htm"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "sass",
			name: "Sass",
			documentationURL: "https://sass-lang.com/documentation/",
			includePaths: [
				"*.sass",
				"*.scss",
				'package.json:"sass"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["css"],
			weight: 2,
		},
		{
			id: "php",
			name: "PHP",
			documentationURL: "https://www.php.net/docs.php",
			includePaths: ["*.php"],
			blacklistedFilenames: [],
			ignoreTechs: ["html"],
			weight: 2,
		},
		{
			id: "composer",
			name: "Composer",
			documentationURL: "https://getcomposer.org/doc/",
			includePaths: ["composer.json", "composer.lock"],
			blacklistedFilenames: ["composer.json", "composer.lock"],
			ignoreTechs: [],
			weight: -1,
		},

		// php frameworks
		{
			id: "laravel",
			name: "Laravel",
			documentationURL: "https://laravel.com/docs/",
			includePaths: ['composer.json:"laravel/framework"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "agavi",
			name: "Agavi",
			documentationURL: "https://github.com/agavi/documentation",
			includePaths: ['composer.json:"agavi/agavi"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "cakephp",
			name: "CakePHP",
			documentationURL: "https://book.cakephp.org/",
			includePaths: ['composer.json:"cakephp/cakephp"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "codeigniter",
			name: "CodeIgniter",
			documentationURL: "https://codeigniter.com/user_guide/",
			includePaths: ['composer.json:"codeigniter?/framework"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "flight",
			name: "Flight",
			documentationURL: "https://flightphp.com/learn/",
			includePaths: ['composer.json:"mikecao/flight""', "*/Flight.php"],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "fuelphp",
			name: "FuelPHP",
			documentationURL: "https://fuelphp.com/docs/",
			includePaths: ['composer.json:"fuel/fuel"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "hoa",
			name: "Hoa",
			documentationURL: "https://github.com/hoaproject",
			includePaths: ['composer.json:"hoa/hoa"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "jelix",
			name: "Jelix",
			documentationURL: "https://jelix.org/articles/en/documentation",
			includePaths: ['composer.json:"jelix/jelix"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "kumbiaphp",
			name: "KumbiaPHP",
			documentationURL:
				"https://github.com/KumbiaPHP/Documentation/tree/master/en",
			includePaths: ['composer.json:"kumbia/kumbia"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "mkframework",
			name: "MKFramework",
			documentationURL: "https://www.mkframework.com/start.html",
			includePaths: ['composer.json:"mkframework/mkframework"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "modx",
			name: "MODX",
			documentationURL: "https://docs.modx.com/current/en/",
			includePaths: ['composer.json:"modx/revolution"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "phalcon",
			name: "Phalcon",
			documentationURL: "https://docs.phalcon.io/",
			includePaths: ['composer.json:"phalcon/phalcon"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "qcodo",
			name: "Qcodo",
			documentationURL: "https://github.com/qcodo/qcodo/blob/master/README.md",
			includePaths: ['composer.json:"qcodo/qcodo"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "slim",
			name: "Slim",
			documentationURL: "https://www.slimframework.com/docs/v4/",
			includePaths: ['composer.json:"slim/slim"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "symfony",
			name: "Symfony",
			documentationURL: "https://symfony.com/doc/",
			includePaths: ['composer.json:"symfony/symfony"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "websitephp",
			name: "WebSitePHP",
			documentationURL: "https://www.website-php.com/fr/documentation.html",
			includePaths: ['composer.json:"website-php/website-php"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "yaf",
			name: "Yaf",
			documentationURL: "https://www.php.net/manual/en/book.yaf.php",
			includePaths: ['composer.json:"yaf/yaf"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "yiiframework",
			name: "Yii Framework",
			documentationURL: "https://www.yiiframework.com/doc/",
			includePaths: ['composer.json:"yiisoft/yii2"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "zendframework",
			name: "Zend Framework",
			documentationURL: "https://docs.laminas.dev/",
			includePaths: ['composer.json:"zendframework/zendframework"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		{
			id: "nette",
			name: "Nette",
			documentationURL: "https://doc.nette.org/en/",
			includePaths: ['composer.json:"nette/utils"'],
			blacklistedFilenames: [],
			ignoreTechs: ["php"],
			weight: 3,
		},
		// -------------------------

		{
			id: "ruby",
			name: "Ruby",
			documentationURL: "https://www.ruby-lang.org/en/documentation/",
			includePaths: ["*.rb"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "cmake",
			name: "CMake",
			documentationURL: "https://cmake.org/cmake/help/latest/",
			includePaths: ["CMakeLists.txt", "*.cmake"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "elixir",
			name: "Elixir",
			documentationURL: "https://elixir-lang.org/docs.html",
			includePaths: ["*.ex", "*.exs"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "lua",
			name: "Lua",
			documentationURL: "https://www.lua.org/docs.html",
			includePaths: ["*.lua"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "alpinejs",
			name: "Alpine.js",
			documentationURL: "https://alpinejs.dev/",
			includePaths: ['package.json:"alpinejs"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: ["javascript"],
			weight: 2,
		},
		{
			id: "angular",
			name: "Angular",
			documentationURL: "https://angular.io/docs",
			includePaths: [
				'package.json:"@angular/core"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: ["typescript"],
			weight: 2,
		},
		{
			id: "dart",
			name: "Dart",
			documentationURL: "https://dart.dev/guides",
			includePaths: ["*.dart"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "flutter",
			name: "Flutter",
			documentationURL: "https://flutter.dev/docs",
			includePaths: ["pubspec.yaml"],
			blacklistedFilenames: ["pubspec.yaml"],
			ignoreTechs: ["dart"],
			weight: 2,
		},
		{
			id: "rust",
			name: "Rust",
			documentationURL: "https://doc.rust-lang.org/",
			includePaths: ["*.rs", "Cargo.toml"],
			blacklistedFilenames: ["Cargo.toml"],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "figma",
			name: "Figma",
			documentationURL: "https://www.figma.com/developers/docs",
			includePaths: ["*.fig", "*.figma"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "renpy",
			name: "Ren'Py",
			documentationURL: "https://www.renpy.org/doc/html/",
			includePaths: ["*.rpy"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "kubernetes",
			name: "Kubernetes",
			documentationURL: "https://kubernetes.io/docs/home/",
			includePaths: ["kubeconfig", "*.k8s.yaml", "*.k8s.yml"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "knexjs",
			name: "Knex.js",
			documentationURL: "https://knexjs.org/guide/",
			includePaths: ['package.json:"knex"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "unity",
			name: "Unity",
			documentationURL: "https://docs.unity3d.com/Manual/index.html",
			includePaths: ["*.unity", "*.prefab"],
			blacklistedFilenames: [],
			ignoreTechs: ["csharp"],
			weight: -1,
		},
		{
			id: "kotlin",
			name: "Kotlin",
			documentationURL: "https://kotlinlang.org/docs/home.html",
			includePaths: ["*.kt", "*.kts"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "android",
			name: "Android",
			documentationURL: "https://developer.android.com/docs",
			includePaths: ["AndroidManifest.xml"],
			blacklistedFilenames: ["AndroidManifest.xml"],
			ignoreTechs: ["java", "kotlin"],
			weight: 2,
		},
		{
			id: "csharp",
			name: "C#",
			documentationURL: "https://www.w3schools.com/cs/",
			includePaths: ["*.cs"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "cpp",
			name: "C++",
			documentationURL: "https://www.w3schools.com/cpp/",
			includePaths: ["*.cpp", "*.cc", "*.c++", "*.C", "*.hpp"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "c",
			name: "C",
			documentationURL: "https://www.w3schools.com/c/",
			includePaths: ["*.c", "*.h"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "go",
			name: "Go",
			documentationURL: "https://go.dev/doc/",
			includePaths: ["*.go"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "gsap",
			name: "GSAP",
			documentationURL: "https://gsap.com/docs/",
			includePaths: ['package.json:"gsap"\\s*:\\s*"(?:\\^|~)?[0-9.]+"'],
			blacklistedFilenames: [],
			ignoreTechs: ["javascript"],
			weight: 2,
		},
		{
			id: "arduino",
			name: "Arduino",
			documentationURL: "https://www.arduino.cc/en/Reference/HomePage",
			includePaths: ["*.ino", "*.pde"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		// secondary technologies

		// CI/CD
		{
			id: "jenkins",
			name: "Jenkins",
			documentationURL: "https://www.jenkins.io/doc/",
			includePaths: ["Jenkinsfile"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: -1,
		},

		// build tools
		{
			id: "gradle",
			name: "Gradle",
			documentationURL: "https://docs.gradle.org/",
			includePaths: ["gradlew", "gradlew.bat", "gradle"],
			blacklistedFilenames: [".gradlew", "gradlew.bat", "gradle"],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "maven",
			name: "Maven",
			documentationURL: "https://maven.apache.org/",
			includePaths: ["mvnw*", ".mvn"],
			blacklistedFilenames: [".mvnw"],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "babel",
			name: "Babel",
			documentationURL: "https://babeljs.io/docs/",
			includePaths: [
				".babelrc",
				'package.json:"babel"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [".babelrc"],
			ignoreTechs: [],
			weight: -1,
		},
		// web bundlers
		{
			id: "vite",
			name: "Vite",
			documentationURL: "https://vite.dev/guide/",
			includePaths: [
				"vite.*config.ts",
				"vite.*config.js",
				".vite",
				'package.json:"vite"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [".vite"],
			ignoreTechs: [],
			weight: -1,
		},
		{
			id: "webpack",
			name: "Webpack",
			documentationURL: "https://webpack.js.org/concepts/",
			includePaths: [
				"webpack.config.ts",
				"webpack.config.js",
				'package.json:"webpack"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: -1,
		},

		// Interpreters
		{
			id: "deno",
			name: "Deno",
			documentationURL: "https://docs.deno.com/",
			includePaths: [
				"deno.json",
				'package.json:"deno"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: ["deno.json"],
			ignoreTechs: ["nodejs"],
			weight: 1,
		},
		{
			id: "bun",
			name: "Bun",
			documentationURL: "https://bun.com/docs/",
			includePaths: [
				"bun.lock",
				"bun.lockb",
				'package.json:"bun"\\s*:\\s*"(?:\\^|~)?[0-9.]+"',
			],
			blacklistedFilenames: ["bun.lock", "bun.lockb"],
			ignoreTechs: ["nodejs"],
			weight: 1,
		},
		// Package Managers
		{
			id: "pnpm",
			name: "pnpm",
			documentationURL: "https://pnpm.io/motivation",
			includePaths: ["pnpm-lock.yaml"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "yarn",
			name: "Yarn",
			documentationURL: "https://classic.yarnpkg.com/en/docs",
			includePaths: ["yarn.lock"],
			blacklistedFilenames: [],
			ignoreTechs: [],
			weight: 1,
		},
		{
			id: "npm",
			name: "npm",
			documentationURL: "https://docs.npmjs.com/",
			includePaths: ["package-lock.json"],
			blacklistedFilenames: ["package-lock.json"],
			ignoreTechs: [],
			weight: 1,
		},
	].toSorted((a, b) => a.weight - b.weight),
) as readonly Technology[];
